complete -c fp -l help -s h -d 'Print usage'
complete -c fp -l version -s v -d 'Print version'
complete -c fp -l lines -s l -r -d 'Specify how many lines of results to show (default 10)'
complete -c fp -l prompt -s p -r -d 'Set the input prompt (default "> ")'
complete -c fp -l query -s q -r -d 'Set the initial search string'
complete -c fp -l show-matches -s e -r -d 'Run non-interactively with the given pattern'
complete -c fp -l tty -s t -r -d 'Specify file to use as TTY device (default /dev/tty)'
complete -c fp -l filter-scores -s f -d 'Filter scores that are over 1 point away from top'
complete -c fp -l show-scores -s s -d 'Show the scores of each match'
complete -c fp -l read-null -s 0 -d 'Read input delimited by ASCII NUL characters'
complete -c fp -l show-info -s i -d 'Show selection info line'
